version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: itmo-chatbot
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
